---
modules-search: [ local ]

instances:
  - id: grub-entries
    module: shellprocess
    config: shellprocess_grub-entries.conf
  - id: lxde-repair
    module: shellprocess
    config: shellprocess_lxde-repair.conf
  - id: normalize-sid
    module: shellprocess
    config: shellprocess_normalize-sid.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initramfscfg
      - initramfs
      - grubcfg
      - bootloader
      - shellprocess@grub-entries
      - shellprocess@lxde-repair
      - shellprocess@normalize-sid
      - packages
      - umount
  - show:
      - finished

branding: debian
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
