---
update_db: true
backend: apt
operations:
  - remove:
      - calamares
      - casper
      - caper
      - cifs-utils
      - discover
      - laptop-detect
      - os-prober
  - try_install:
      - hunspell-$LOCALE
      - libreoffice-help-$LOCALE
      - libreoffice-l10n-$LOCALE

