---
defaultPartitionTableType: gpt

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB

enableLuksAutomatedPartitioning: true
luksGeneration: luks2

userSwapChoices:
  - none
initialSwapChoice: none

drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]

partitionLayout:
  - name: "debian_boot"
    filesystem: ext4
    noEncrypt: true
    onlyPresentWithEncryption: true
    mountPoint: "/boot"
    size: 4G
  - name: "debian_swap"
    filesystem: linuxswap
    size: 4G
  - name: "debian_root"
    filesystem: unknown
    mountPoint: "/"
    size: 100%

