---
dontChroot: false
timeout: 300
script:
  - |
      bash -ec '
      if [ -f /etc/os-release ] && grep -qi "sid\|unstable" /etc/os-release; then
        cat << "EOF" > /etc/os-release
      PRETTY_NAME="Debian GNU/Linux Sid"
      NAME="Debian GNU/Linux"
      VERSION_CODENAME=sid
      ID=debian
      HOME_URL="https://www.debian.org/"
      SUPPORT_URL="https://www.debian.org/support"
      BUG_REPORT_URL="https://bugs.debian.org/"
      EOF
        if [ -f /usr/lib/os-release ] && ! [ /etc/os-release -ef /usr/lib/os-release ]; then
          cp -f /etc/os-release /usr/lib/os-release
        fi
        if [ -f /etc/debian_version ]; then
          sed -i "s#[^/[:space:]]*/sid#sid#g" /etc/debian_version
        fi
      fi
      exit 0
      '
